# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fernando Cejas
email: fcejas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome! I'm Fernando Cejas, Core Engineer working at @SoundCloud.<br>
  In this blog, you will find content related to software engineering.<br> 
  All views, posts and opinions shared are my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fernando_cejas
github_username:  android10

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Theme settings: https://github.com/pages-themes/cayman
google_analytics: UA-17189586-4

# Custom settings:
twitter_url: https://twitter.com/fernando_cejas
github_url: https://github.com/android10
linkedin_url: https://www.linkedin.com/in/fernandocejas/
speakerdeck_url: https://speakerdeck.com/android10 


